# The configuration file for SkyHoppers.

# Should Mined Hoppers instantly go into the player's inventory?
insta-pickup: false

# How many ticks should there between each item transfer.
transfer-ticks: 10

# How many items per 'transfer-ticks' should be transferred wirelessly?
items-per-transfer: 2

# The range (In blocks) that a hopper can pick up items.
suction-range: 5.0

# Design the Hopper Item
hopper:
  name: '#99ff99&lSky Hopper'
  lore:
    - '&7Wirelessly transfer any item from this'
    - '&7hopper to any container & suction'
    - '&7a full chunk of resources!'
    - ' '
    - ' &f&m-----------------'
    - ' &f| #99ff99&lEnabled &7: &f%enabled%'
    - ' &f| #99ff99&lContainer &7: &f%linked%'
    - ' &f| #99ff99&lFilter &7: &f%filterType%'
  glow: true

# Configure SQL Saving, MySQL is absolutely not recommended if you're using this on multiple servers
# but mysql does do data faster so up to you.
mysql:
  enabled: false
  host: localhost
  port: 3306
  dbname: DBName
  username: Username
  password: Password
  ssl: true