name: SkyHoppers
main: xyz.oribuin.skyhoppers.SkyHoppersPlugin
version: '@version@'
api-version: '1.16'
author: Oribuin
description: A chunk hopper plugin with wireless transfer, item filters and chunk suction.
softdepend:
  - PlaceholderAPI
  - WildStacker
  - RoseStacker
  - BentoBox
  - Lands
  - Towny
  - WorldGuard
  - IridiumSkyblock