name: SkyHoppers
main: net.oribuin.skyhoppers.SkyHoppersPlugin
version: '1.0.2'
api-version: '1.16'
author: Oribuin
description: A chunk hopper plugin with wireless transfer, item filters and chunk suction.
softdepend:
  - PlaceholderAPI
  - WorldGuard
  - RoseStacker
  - BentoBox